### ISSUE TITLE
MultipleSelectAddNext()

### ISSUE THREAD

**Issue by CennoxX** [dail8859/BetterMultiSelection#12]
Does this plugin add a shortcut for Scintilla’s `MultipleSelectAddNext()`? This is the well known `[ctrl]`+`[d]` shortcut from sublime. With the new Scintilla API this should be easyto integrate (https://notepad-plus-plus.org/community/topic/17626/plugin-update-luascript-v0-9-supports-scintilla-v4-1-4).

**Comment by dail8859** [comment]
> Does this plugin add a shortcut for Scintilla’s MultipleSelectAddNext()?

No it does not. The main reason for this plugin was to hook the keyboard input (before Notepad++ sees it) since the multi selection "shortcuts" (up, down, left, right, etc) are not map-able to real Windows "shortcuts".

If you do want the capability I recommend either waiting until Notepad++ supports it (no clue if/when that would be) or I'd recommend using LuaScript.
