### ISSUE TITLE
entire file Multi Cursor feature request

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [dail8859/BetterMultiSelection#7]
First of all thanks for this great plugin! Do you think there is an easy way to implement multiline selection on an entire file? It would be incredibly useful on large files with thousands of lines, to press for example Shift + Alt + End/Start in order to have a multi-cursor on the entire file.

**Comment by dail8859** [comment]
This seems a little out of scope for this particular project because it comes down to just making a rectangular selection.

The easiest way to do it would be place the cursor at the top of the file, scroll to the bottom, then `Ctrl+Alt+Click` the beginning of the last line. That would make a rectangular selection on the entire file then you can edit every line a the same time.

Your other option would be to use a plugin such as LuaScript and create a shortcut to do it yourself. For example this mostly works:

```lua
npp.AddShortcut("Multi Cursor All Lines", "Ctrl+Alt+Shift+F1", function()
	editor.RectangularSelectionAnchor = 0
	editor.RectangularSelectionCaret = editor:PositionFromLine(editor.LineCount - 1)
end)
```
